Sea forecast associated with closest sea station
dgomes/pyipma pull request #9
Opened 2020-04-15 23:02 UTC by joaocps

-> Aproveitei a Classe ForecastLocation pra criar o objeto das sea_stations e consequentemente ver qual era a estação maritima mais proxima. A previsão para o estado do mar é feita para o dia de hoje mas a api do ipma permite fazer a previsão para até 3 dias, pode-se mudar com facilidade!

Veja se interessa, aproveitei para praticar a poo e o async !

2020-04-15 23:07 UTC, dgomes requested changes
Many Tks!

Devia haver um argumento algures na criação do objecto Location para tornar isto opcional.

Não faz sentido qd a tua localização é Bragança :)

2020-04-15 23:07 UTC, dgomes commented on pyipma/consts.py
> +API_SEA_LOCATIONS = "http://api.ipma.pt/open-data/sea-locations.json"
junta estas APIS com as de cima

Se vires bem eu separei as _public-data_ das _open-data_

2020-04-15 23:29 UTC, joaocps commented on pyipma/consts.py
> +API_SEA_LOCATIONS = "http://api.ipma.pt/open-data/sea-locations.json"
Done :)

2020-04-16 20:43 UTC, joaocps commented
> Many Tks!
> 
> Devia haver um argumento algures na criação do objecto Location para tornar isto opcional.
> 
> Não faz sentido qd a tua localização é Bragança :)

Estou a perceber, mas fará mais sentido no momento do pedido feito pelo cliente?

Tipo no `location = await Location.get(api,  40.6517, -8.6573, allow_sea_locattions = True)`

Ou na altura da criação do objeto?
`t_loc = Location(location, station, sea_station, weather_type)`, em que o argumento de sea station só é passado quando a distancia à estação maritima for inferior a x ...

Ou outro opção qualquer :rofl:

2020-04-16 21:49 UTC, dgomes commented
Acho que um argumento opcional em Location que pode estar por default em False

2020-04-17 21:35 UTC, dgomes commented on pyipma/location.py
> +    async def get(cls, api, lat, lon, allow_sea_stations=False, l_order=0, s_order=0, t_order=0):
em vez de `allow_sea_stations` pode ficar só `sea_station`

2020-04-17 21:38 UTC, dgomes requested changes
aqueles s_order, l_order, t_order depois precisam de um refactor pq já não significam nada 🗡️

2020-04-17 21:38 UTC, dgomes commented on pyipma/location.py
> +            return "Sea stations disabled"
return None

2020-04-17 21:38 UTC, dgomes commented on pyipma/location.py
> +            return "Sea stations disabled"
Return None

2020-04-17 21:48 UTC, joaocps commented
> aqueles s_order, l_order, t_order depois precisam de um refactor pq já não significam nada

Já me tinha esquecido disso !

2020-04-17 22:02 UTC, joaocps commented
Mesmo com o sea_station = False, podemos passar o t_order=0 default não?

2020-04-17 22:36 UTC, dgomes requested changes

2020-04-17 22:36 UTC, dgomes commented on pyipma/location.py
> +                return await cls.get(api, lat, lon, True, l_order, s_order, t_order + 1)
este `True` não devia ser `sea_stations` ?

2020-04-17 22:36 UTC, dgomes commented on pyipma/location.py
> +            return await cls.get(api, lat, lon, False, l_order + 1, s_order, t_order)
e aqui tb sea_stations ?

(pergunta honesta... estou cansado :) )

2020-04-17 22:53 UTC, dgomes approved these changes

2020-04-17 22:53 UTC, joaocps commented on pyipma/location.py
> +            return await cls.get(api, lat, lon, False, l_order + 1, s_order, t_order)
Exato ahah, apesar de ir funcionar tudo na mesma! xD

2020-04-17 22:53 UTC, merged